### PR TITLE
Ipywidgets 7

### LINKED ISSUE #15: interactive_stream throwing a widget error in Python 3.9
In a clean Conda environment I pip installed scikit-dsp-comm and pyaudio_helper. I then tried to run a demo notebook and realized changes to the module requires some names changes in both method names and arguments. Working through this I received this error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/58/hy23wcvd6t1g3s0djl92ptbm0000gn/T/ipykernel_11645/2678760716.py in <module>
      3 DSP_IO = pah.DSPIOStream(callback,0,2,fs = 44100,t_capture = 0)
      4 # DSP_IO = pah_old.DSP_io_stream(callback,0,2,fs = 44100,Tcapture = 0)
----> 5 DSP_IO.interactive_stream(t_sec = 0, num_chan = 2)
      6 # DSP_IO.interactive_stream(Tsec=0,numChan=2)
      7 widgets.HBox([L_gain, R_gain])

~/opt/miniconda3/envs/dsp-comm39/lib/python3.9/site-packages/sk_dsp_comm/pyaudio_helper/pyaudio_helper.py in interactive_stream(self, t_sec, num_chan)
    146         self.numChan = num_chan
    147         self.interactiveFG = 1
--> 148         self.play = interactive(self.interaction, Stream=ToggleButtons(
    149             options=['Start Streaming', 'Stop Streaming'],
    150             description=' ',

~/opt/miniconda3/envs/dsp-comm39/lib/python3.9/site-packages/ipywidgets/widgets/interaction.py in __init__(self, _interactive__interact_f, _interactive__options, **kwargs)
    186         self.auto_display = __options.get("auto_display", False)
    187 
--> 188         new_kwargs = self.find_abbreviations(kwargs)
    189         # Before we proceed, let's make sure that the user has passed a set of args+kwargs
    190         # that will lead to a valid call of the function. This protects against unspecified

~/opt/miniconda3/envs/dsp-comm39/lib/python3.9/site-packages/ipywidgets/widgets/interaction.py in find_abbreviations(self, kwargs)
    286             for name, value, default in _yield_abbreviations_for_parameter(param, kwargs):
    287                 if value is empty:
--> 288                     raise ValueError('cannot find widget or abbreviation for argument: {!r}'.format(name))
    289                 new_kwargs.append((name, value, default))
    290         return new_kwargs

ValueError: cannot find widget or abbreviation for argument: 'stream'
```

In the first traceback listing you can see commented lines 4 and 6 make use of the old version of pyaudio_helper.py. When this code is run all is well in the Python 3.9 environment. Note I am listing below version numbers for some of the ipython and Jupiter components:

ipykernel                 6.0.3            py39h71a6800_0    conda-forge
ipython                   7.25.0           py39h71a6800_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
jbig                      2.1               h0d85af4_2003    conda-forge
jedi                      0.18.0           py39h6e9494a_2    conda-forge
jinja2                    3.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py39h6e9494a_0    conda-forge
jupyter_server            1.10.1             pyhd8ed1ab_0    conda-forge
jupyterlab                3.0.16             pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.6.1              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge

I looking at a file diff between the old and newer versions and so far nothing jumps off the page.

### PR DESCRIPTION
**Pull request by chiranthsiddappa**
This branch has incorporated the new IPywidgets API and some refactoring of the DSPIOStream class. portaudio threw a few errors on my system, so this will require a run through before merging and releasing a new version.

### CODE REVIEW

**Comment by mwickert** [comment]
What would like me to do to test this? Should lI just grab the code module and try it out stand-alone?

FYI, in my DSP lecture and Lab classes I am supplying them with the old pyaudio_helper.py module (I renamed it to pyaudio_helper_old.py) and we are moving forward on Python 3.9.

**Comment by chiranthsiddappa** [comment]
Yes, it will be have to tested standalone for now. I need to work on updating the notebook example and that will be done next in #17 .

**Comment by mwickert** [comment]
I cannot get the new code to work, even after fixing some errors. I am running on Win10 for the test and starting with Python 3.7 and then will test with Python 3.9. After my fixes code runs but to start and stop buttons:
image
My modifications were all made to pyaudio_helper.py. I am attaching the file.

At line 43-44 area this
`# from . interactive_widgets import InteractiveWidgets
from interactive_widgets import InteractiveWidgets`

At line 150 area I commented if t_sec ... line and then added a comment near self.create
`        self.Tsec = t_sec #if t_sec else self.Tsec
        self.numChan = num_chan if num_chan else self.numChan
        self.interactiveFG = True
        return 
    
# This line of code seems misplaced?    
self.create_interactive_widgets(start_handler=self.start_stream_interactive_callback,
                                               stop_handler=self.stop_stream_interactive_callback)`

I realize you have made some changes to function naming to be more consistent with Python PEP8, but other than that what is wrong with the old version of the `pyaudio_helper` code? I works just for me under Python 3.9.

**Comment by chiranthsiddappa** [comment]
There were a few missing variables that started out undefined, and they have been added to the main class. They were originally set directly, but now allow a consistent usage of the optional param against the class variable names.

The original `pyaudio_helper` code was written with a much older version of ipywidgets. In #15  I noticed `ipywidgets==7.6.3` so the code in this branch brings in the required changes to use this version. The docs on the main branch now reflect the correct usage for the widgets.

```python
DSP_IO = pah.DSPIOStream(callback,0,1,fs=48000,t_capture=0)
start_stop_buttons = DSP_IO.interactive_stream(0,2)
widgets.VBox([start_stop_buttons, widgets.HBox([L_gain, R_gain])])
```

**Pull request merged**
